export { default as login } from './login'
export { default as register } from './register'
export { default as sendOTP } from './sendOTP'
export { default as confirmOTP } from './confirmOTP'
export { default as isActivated } from './isActivated'