import { useState } from 'react';
import { addBookRef, BookReference } from '../../../services/Curriculum/BookReferenceService';

const useAddBookRef = () => {
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<Error | null>(null);
    const [success, setSuccess] = useState<boolean | null>(null);

    const addNewBookRef = async (courseId: number, courseName: string, book: Book) => {
        setIsLoading(true);
        setError(null);
        setSuccess(null);

        try {
            const newBookRef: BookReference = {
                id: 0, // Assuming this is auto-generated by the backend
                course_id: courseId,
                course_name: courseName,
                book_id: book.id,
                book_name: book.title,
                isbn10: book.isbn10,
                isbn13: book.isbn13,
                language: book.language,
                location: book.location,
                status: 1 // Assuming status 1 means active or added
            };
            const addedBookRef = await addBookRef(newBookRef);
            setSuccess(true);
            return addedBookRef;
        } catch (err: any) {
            setError(err);
            setSuccess(false);
            throw err;
        } finally {
            setIsLoading(false);
        }
    };

    return {
        addNewBookRef,
        isLoading,
        error,
        success,
    };
};

export default useAddBookRef;