import { useState } from "react";
import { addMultipleBookRef, BookReference } from "../../../services/Curriculum/BookReferenceService";

const useAddMultipleBookRef = () => {
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<Error | null>(null);
    const [success, setSuccess] = useState<boolean | null>(null);

    const addNewMultipleBookRef = async (courseId: number, courseName: string, books: Book[]) => {
        setIsLoading(true);
        setError(null);
        setSuccess(null);

        try {
            const newBookRefs: BookReference[] = books.map((book) => ({
                id: 0, // Assuming auto-generated by the backend
                course_id: courseId,
                course_name: courseName,
                book_id: book.id,
                book_name: book.title,
                isbn10: book.isbn10,
                isbn13: book.isbn13,
                language: book.language,
                location: book.location,
                status: 1, // Assuming status 1 means active or added
            }));

            const addedBookRefs = await addMultipleBookRef(newBookRefs);
            setSuccess(true);
            return addedBookRefs;
        } catch (err: any) {
            setError(err);
            setSuccess(false);
            throw err;
        } finally {
            setIsLoading(false);
        }
    };

    return {
        addNewMultipleBookRef,
        isLoading,
        error,
        success,
    };
};

export default useAddMultipleBookRef;